query Rockets {
  rockets {
    active
    boosters
    company
    cost_per_launch
    country
    description
    diameter {
      feet
      meters
    }
    engines {
      engine_loss_max
      layout
      number
      propellant_1
      propellant_2
      thrust_sea_level {
        kN
        lbf
      }
      thrust_to_weight
      thrust_vacuum {
        kN
        lbf
      }
      type
      version
    }
    first_flight
    first_stage {
      burn_time_sec
      engines
      fuel_amount_tons
      reusable
    }
    height {
      feet
      meters
    }
    id
    landing_legs {
      material
      number
    }
    mass {
      kg
      lb
    }
    name
    payload_weights {
      id
      kg
      lb
      name
    }
    second_stage {
      burn_time_sec
      engines
      fuel_amount_tons
      payloads {
        composite_fairing {
          diameter {
            meters
          }
          height {
            meters
          }
        }
        option_1
      }
      thrust {
        kN
        lbf
      }
    }
    stages
    success_rate_pct
    type
    wikipedia
  }
}